[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API代理到本地后端 (使用localtunnel)
[[redirects]]
  from = "/api/*"
  to = "https://metal-kiwis-thank.loca.lt/api/:splat"
  status = 200
  force = true